package org.gnucash.api.read.impl.hlp;

/*
 * In this interface, we assume that the numbers of customers, vendors, 
 * employees and jobs (note: the numbers, not the internal GUIDs) are all 
 * as generated by default, i.e.; a) one letter as prefix, b) the rest 
 * is a padded integer, starting at 1.
 * 
 * CAUTION:
 * For customers, vendors and employees, this may typically be usual and 
 * effective. For jobs, however, things are typically different, so think 
 * twice before using the job-methods!
 */
public interface GnuCashPubIDManager {

    String PADDING_TEMPLATE = "000000";
    
    // ---------------------------------------------------------------

    int getHighestCustomerNumber();

    int getHighestVendorNumber();

    int getHighestEmployeeNumber();

    int getHighestJobNumber();
    
    // ----------------------------

    String getNewCustomerNumber();

    String getNewVendorNumber();

    String getNewEmployeeNumber();

    String getNewJobNumber();

}
